apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- abc-customer-backend-app-deployment.yaml
- abc-customer-backend-app-service.yaml
- ingress-service.yaml

images:
- name: CUSTOMER/BACKEND/IMAGE
  newName: udithkavdoc/abc-customer-backend-app
