name: This a workflow title 
on: [push] # When pushing to any branch then run this action
# Env variable
env:
  DOCKER_USER: ${{secrets.DOCKER_USER}}
  DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
  FRONTEND_REPO_NAME: abc-frontend-app
  PRODUCT_BACKEND_REPO_NAME: abc-product-backend-app
jobs:
  push-image-to-docker-hub-and-deploy:  # job name
    runs-on: ubuntu-latest  # runner name : (ubuntu latest version) 
    steps:
    - uses: actions/checkout@v2 # first action : checkout source code
    - name: docker login
      run: | # log into docker hub account
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD  

      
      
    - name: Build frontend image and push to Docker Hub and GitHub Container Registry
      uses: docker/build-push-action@v2
      with:
        context: ./abc-frontend-app
        push: true
        tags: ${{secrets.DOCKER_USER}}/abc-frontend-app:$(date +%s)
        
      
    - name: Build product image and push to Docker Hub and GitHub Container Registry
      uses: docker/build-push-action@v2
      with:
        context: ./abc-product-backend-app
        push: true
        tags: ${{secrets.DOCKER_USER}}/abc-product-backend-app:$(date +%s)

